### ISSUE TITLE
Undefined index: value on line 32 of Plugin.php

### ISSUE THREAD

**Issue by mocbuhtig** [mjauvin/wn-stripe-plugin#2]
I just installed the plugin and everytime I click on Save I get this error, even if I make no change.

`"Undefined index: value" on line 32 of /plugins/studioazura/stripe/Plugin.php`

**Comment by mjauvin** [comment]
odd, let me take a look and I'll get back to you.

**Comment by mjauvin** [comment]
I have a fix for you, give me a few minutes to update the plugin.

**Comment by mjauvin** [comment]
Try to update, version 1.0.5 fixes the issue.

Thanks for reporting this.

**Comment by mjauvin** [comment]
Please let me know how the integration goes, I know the documentation needs love, so any insight, PRs, etc, are welcome.

**Comment by mocbuhtig** [comment]
The fix worked thank you.

I'm not a dev so I'm a little puzzled by the documentation. I created a page and pasted the code like you did on the screenshot. When browsing that page it displays a checkout button and when clicked it adds default values to the URL, but I don't know where/how to create a custom payment button, or form.

**Comment by mjauvin** [comment]
Under your theme's folder, create a `partials/stripeCheckout` folder and duplicate the "default.htm" view file from the component in there.

Just modify that view file to your liking. You can specify the order details either in the viewBag component or in the form itself.

Let me know if that helps.

**Comment by mocbuhtig** [comment]
> Under your theme's folder, create a `partials/stripeCheckout` folder and duplicate the "default.htm" view file from the component in there.

I did that. Thanks. Now figuring out how to add this partial to a static page, I'll watch the tutorials.

**Comment by mjauvin** [comment]
Add this to `Plugin.php`:
```
    public function registerPageSnippets()
    {   
        return [
            'StudioAzura\Stripe\Components\Stripe' => 'stripe',
            'StudioAzura\Stripe\Components\Checkout' => 'stripeCheckout',
        ];
    }
```

In order to use in Static Pages.
